### PR TITLE
Hotfix/reference remove

### LINKED ISSUE #365: Reference stand alone module
Reference does not work as a module shipping within Punchcard.

```gherkin
Feature: Reference in CMS
  As an implementor
  I want references to be available to use in my forms
  So that I can use references in my CMS.

  Scenario: Reference module
    Given reference needs to be accessible as an npm module
     When I want to use the reference input plugin
     Then I should be able to include it as a dependency in my module

  Scenario: Remove reference
    Given that reference is a plugin inside Punchcard
      And that I need to extricate it from Punchcard and make a standalone module
      And I need Punchcard to work with the reference module
    When I want to use Punchcard to create a CMS
    Then I can create content which references other content
      And I only need to include references as a dependency to make it work
      And I can use Punchcard without reference as a dependency and it does not error.
```

---

**Reference in CMS**
- [x] Reference module
- [x] Remove reference

### PR DESCRIPTION
**Pull request by scottnath**
Reference plugin required to be removed for when Punchcard used as a module

---
Resolves #365 

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

**Comment by Snugug** [comment]
@scottnath out of date

**Comment by scottnath** [comment]
@Snugug updated and passed tests

**Comment by Snugug** [comment]
Please explain to me why this isn't working as expected before we remove this

**Comment by scottnath** [comment]
The reason this doesn't work is that when we make local input plugins in an app using the reference input plugin, then we cannot use `require` because node cannot find any `require`'s unless they are in node_modules. The only other option is to have an export from punchcard of the plugin - but then that means that no multi-input plugins could be made and shipped via npm unless they use `punchcard` as a dependency. That was what [this bug](https://github.com/punchcard-cms/punchcard/issues/364) was for.

**Comment by Snugug** [comment]
Does this now work? Have you done a full integration test with an instance to confirm this is indeed working as expected?

**Comment by Snugug** [comment]
Everything works as expected currently, with the following bug:

* Config initialization needs to happen before database initialization

That should be how we move forward with reference. Input plugins can require reference by doing `const reference = require('punchcard-cms/input-plugins/input-plugin-reference');`. For input plugins distributed via NPM, they should set punchcard as a peerDependency.

Closing this in favor of this bug fix, then references work.

**Pull request closed without merging**
