### PR TITLE
Hotfix/e2e refactor: all content types, one content type

### PR DESCRIPTION
**Pull request by scottnath**
This is a code refactor for the landing pages for all content types and for a single content type.

PR created for feedback.

---
Resolves n/a

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

**Comment by Snugug** [comment]
Stalled out on the DB test. Why is that giving us issues? Restarted the build

**Comment by Snugug** [comment]
@scottnath This looks good! Only real thought is [nextCalled](https://github.com/punchcard-cms/punchcard/pull/267/files#diff-d1252a2dc54b98ab4ca3af89534e4fb9R11) you may have some race conditions with as everything's touching it?

**Comment by Snugug** [comment]
Coverage is only down 15%!

**Comment by scottnath** [comment]
closing...need to make a new PR

**Pull request closed without merging**
