### PR TITLE
Feature/route updates

### PR DESCRIPTION
**Pull request by scottnath**
Fixing the content routes and adding tests. These changes are required to move forward on workflows.

---
Resolves #

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

**Comment by rachelnicole** [comment]
seems fine as long as CI builds

**Comment by ayush2k** [comment]
@scottnath 
👍

**Comment by scottnath** [comment]
@rachelnicole can you please merge this in?

**Comment by rachelnicole** [comment]
@scottnath yeahhhhh

**Pull request merged**
